anguage: ruby
rvm:
  - 2.4.0
before_script:
  - cp config/database.travis.yml config/database.yml
script:
  - bundle exec rails db:create db:migrate db:seed
  - bundle exec rspec
services:
  - postgresql
notifications:
  email: false
